-- SQL script to insert remaining 51 teams into Supabase 'teams' table
-- Run this script in your Supabase SQL Editor

INSERT INTO teams (name, institution, total_points, status, metrics, last_updated, run_history, tags)
VALUES
('Code Geass', 'EEE - 2', 0, 'Registered', '{"password": "HWGQ49"}'::jsonb, 'Just now', '[]'::jsonb, '["Aamrrish G R (EEE - 2)", "Mithul Pranav M (EEE - 2)"]'::jsonb),
('Simvengers', 'BME - 2', 0, 'Registered', '{"password": "6RAFHU"}'::jsonb, 'Just now', '[]'::jsonb, '["Anirudh H (BME - 2)", "Gargi Pansari (BME - 2)"]'::jsonb),
('Twinvolt', 'EEE - 3', 0, 'Registered', '{"password": "G6A9WP"}'::jsonb, 'Just now', '[]'::jsonb, '["Mirthika S (EEE - 3)", "Neha S (EEE - 3)"]'::jsonb),
('Sana and Sugaa', 'EEE - 2', 0, 'Registered', '{"password": "3SYY2E"}'::jsonb, 'Just now', '[]'::jsonb, '["Sahana Gopalakrishnan (EEE - 2)", "Sugaasri S (EEE - 2)"]'::jsonb),
('Double takkar', 'BME - 2', 0, 'Registered', '{"password": "XFUU7K"}'::jsonb, 'Just now', '[]'::jsonb, '["Inbaa R (BME - 2)", "Harshini.R.S (BME - 2)"]'::jsonb),
('Royal super simulators', 'BME - 2', 0, 'Registered', '{"password": "VBZZ75"}'::jsonb, 'Just now', '[]'::jsonb, '["Abhijeth (BME - 2)", "Rithik (BME - 2)"]'::jsonb),
('NOVA', 'ECE - 3', 0, 'Registered', '{"password": "F39H59"}'::jsonb, 'Just now', '[]'::jsonb, '["Madeshwaran M (ECE - 3)", "Janani M (ECE - 3)"]'::jsonb),
('Supernova', 'BME - 2', 0, 'Registered', '{"password": "3S48BQ"}'::jsonb, 'Just now', '[]'::jsonb, '["GS Shai Manisha (BME - 2)", "Shriya B (BME - 2)"]'::jsonb),
('PulseForge', 'EEE - 3', 0, 'Registered', '{"password": "JDG58K"}'::jsonb, 'Just now', '[]'::jsonb, '["Niveditha V (EEE - 3)", "Pankaj Singh (EEE - 3)"]'::jsonb),
('Sahana S', 'ECE - 2', 0, 'Registered', '{"password": "8QH78S"}'::jsonb, 'Just now', '[]'::jsonb, '["Sahana S (ECE - 2)", "Shri Bargavi S (ECE - 2)"]'::jsonb),
('TeamX', 'EEE - 3', 0, 'Registered', '{"password": "3V835N"}'::jsonb, 'Just now', '[]'::jsonb, '["Kesava Kailash M T (EEE - 3)"]'::jsonb),
('Celestial', 'ECE - 2', 0, 'Registered', '{"password": "UTACK7"}'::jsonb, 'Just now', '[]'::jsonb, '["Vikrant R.M (ECE - 2)"]'::jsonb),
('Two phase', 'EEE - 2', 0, 'Registered', '{"password": "9ZNS97"}'::jsonb, 'Just now', '[]'::jsonb, '["Perarasu.J (EEE - 2)", "Vishnudharan.M (EEE - 2)"]'::jsonb),
('Pairfect', 'BME - 3', 0, 'Registered', '{"password": "95CUW7"}'::jsonb, 'Just now', '[]'::jsonb, '["Priscilla Christy S (BME - 3)", "Kiruthika U (BME - 3)"]'::jsonb),
('Simu Techiezz', 'ECE - 2', 0, 'Registered', '{"password": "G6S6M5"}'::jsonb, 'Just now', '[]'::jsonb, '["Sanjay L (ECE - 2)", "Sanjay S (ECE - 2)"]'::jsonb),
('Sytrus', 'EEE - 2', 0, 'Registered', '{"password": "8ET9ZG"}'::jsonb, 'Just now', '[]'::jsonb, '["Harshini Devi (EEE - 2)", "Aashish S (EEE - 2)"]'::jsonb),
('MATRIXMinds', 'EEE - 2', 0, 'Registered', '{"password": "N4K6AF"}'::jsonb, 'Just now', '[]'::jsonb, '["Jaffy Sardonyx R (EEE - 2)", "Madhumitha A (EEE - 2)"]'::jsonb),
('Power Rangers', 'EEE - 2', 0, 'Registered', '{"password": "A6FNRH"}'::jsonb, 'Just now', '[]'::jsonb, '["R.Kritheesh (EEE - 2)", "Antony Kilfrin Wilson (EEE - 2)"]'::jsonb),
('DC', 'EEE - 2', 0, 'Registered', '{"password": "CTYKAW"}'::jsonb, 'Just now', '[]'::jsonb, '["Lakshithnaren.S (EEE - 2)", "Kishore M (EEE - 2)"]'::jsonb),
('Dual Potential', 'ECE - 2', 0, 'Registered', '{"password": "9JQ8JU"}'::jsonb, 'Just now', '[]'::jsonb, '["Shrivatsan Raja B (ECE - 2)", "Sri Amrita B (ECE - 2)"]'::jsonb),
('Steady State', 'ECE - 2', 0, 'Registered', '{"password": "F4LJV4"}'::jsonb, 'Just now', '[]'::jsonb, '["Sakthi Sundara Murthy K S (ECE - 2)", "Mahalakshmi K (ECE - 2)"]'::jsonb),
('Matrixes', 'ECE - 2', 0, 'Registered', '{"password": "2KN2AG"}'::jsonb, 'Just now', '[]'::jsonb, '["Aswin Sundaravadivelu (ECE - 2)"]'::jsonb),
('Jarvis', 'ECE - 3', 0, 'Registered', '{"password": "2EDYYB"}'::jsonb, 'Just now', '[]'::jsonb, '["Divyakriti Prabhu Uma (ECE - 3)", "Aravind Krishna (ECE - 3)"]'::jsonb),
('Earth616', 'EEE - 2', 0, 'Registered', '{"password": "B8WV6W"}'::jsonb, 'Just now', '[]'::jsonb, '["Vibodh Ramanan (EEE - 2)", "Pradhosh S (EEE - 2)"]'::jsonb),
('No more mutants', 'EEE - 3', 0, 'Registered', '{"password": "H97LKP"}'::jsonb, 'Just now', '[]'::jsonb, '["Mithreshwar CM (EEE - 3)", "Jai muthukumaran J (EEE - 3)"]'::jsonb),
('Ctrl+Alt+Defeat', 'MECH - 2', 0, 'Registered', '{"password": "5X7QE3"}'::jsonb, 'Just now', '[]'::jsonb, '["P Shreyas (MECH - 2)", "Madhumita V J (CHEM - 2)"]'::jsonb),
('okaynga', 'BME - 2', 0, 'Registered', '{"password": "CNMCD6"}'::jsonb, 'Just now', '[]'::jsonb, '["Dhanya Mahalakshmi R (BME - 2)", "Sharada Shree G (BME - 2)"]'::jsonb),
('Simcy', 'EEE - 2', 0, 'Registered', '{"password": "N8BJPJ"}'::jsonb, 'Just now', '[]'::jsonb, '["Hashim Mohamed Farook. H (EEE - 2)", "Bharani. K (EEE - 2)"]'::jsonb),
('Sync logic', 'EEE - 3', 0, 'Registered', '{"password": "LM2T54"}'::jsonb, 'Just now', '[]'::jsonb, '["Prisca Jean D (EEE - 3)", "Ramprasad B (EEE - 3)"]'::jsonb),
('CodeCore', 'BME - 2', 0, 'Registered', '{"password": "F2VMYM"}'::jsonb, 'Just now', '[]'::jsonb, '["Sreenithi S (BME - 2)", "Ajay Karthic (BME - 2)"]'::jsonb),
('Sharp Minds', 'ECE - 2', 0, 'Registered', '{"password": "S794U7"}'::jsonb, 'Just now', '[]'::jsonb, '["Surya SS (ECE - 2)", "Yashwanth Vijay (ECE - 2)"]'::jsonb),
('Ohmies for Life', 'EEE - 3', 0, 'Registered', '{"password": "MW86HT"}'::jsonb, 'Just now', '[]'::jsonb, '["GOKULRAJ S L (EEE - 3)", "ASHWAANTH R S (EEE - 3)"]'::jsonb),
('S', 'EEE - 2', 0, 'Registered', '{"password": "GPQAF7"}'::jsonb, 'Just now', '[]'::jsonb, '["Sanjay Vinayak (EEE - 2)"]'::jsonb),
('Circuit Ninjas', 'ECE - 2', 0, 'Registered', '{"password": "X4MBYL"}'::jsonb, 'Just now', '[]'::jsonb, '["T Tharunn (ECE - 2)", "Shivani M (ECE - 2)"]'::jsonb),
('Matlab Mayavigal', 'ECE - 2', 0, 'Registered', '{"password": "YPHTPU"}'::jsonb, 'Just now', '[]'::jsonb, '["Yuvaraj V (ECE - 2)", "Srihari R V (ECE - 2)"]'::jsonb),
('Kairova', 'CSE - 2', 0, 'Registered', '{"password": "TJGSG5"}'::jsonb, 'Just now', '[]'::jsonb, '["Benita Brightly (CSE - 2)", "Priyanka M (CSE - 2)"]'::jsonb),
('Peanut Butter', 'EEE - 3', 0, 'Registered', '{"password": "LGDYMG"}'::jsonb, 'Just now', '[]'::jsonb, '["Hemanth M (EEE - 3)", "Faizaan M (EEE - 3)"]'::jsonb),
('Simmates', 'ECE - 2', 0, 'Registered', '{"password": "WTEUWL"}'::jsonb, 'Just now', '[]'::jsonb, '["LAKSHMI PRIYA R (ECE - 2)", "AKSHAYAA S A (ECE - 2)"]'::jsonb),
('Tokyo Drifters', 'ECE - 3', 0, 'Registered', '{"password": "SSEA4S"}'::jsonb, 'Just now', '[]'::jsonb, '["Vignesh Manikandan V (ECE - 3)", "Shyam MR (ECE - 3)"]'::jsonb),
('Dual sharks', 'BME - 2', 0, 'Registered', '{"password": "4ADGRB"}'::jsonb, 'Just now', '[]'::jsonb, '["Rishmitha R (BME - 2)", "Merlin Amrutha .E (BME - 2)"]'::jsonb),
('Dual Sparks', 'BME - 2', 0, 'Registered', '{"password": "VHGYW7"}'::jsonb, 'Just now', '[]'::jsonb, '["Merlin Amrutha E (BME - 2)", "Rishmitha R (BME - 2)"]'::jsonb),
('CannonBolt', 'BME - 2', 0, 'Registered', '{"password": "C3WP75"}'::jsonb, 'Just now', '[]'::jsonb, '["Neha S (BME - 2)", "Raja Anbu Chelvan A P (MECH - 2)"]'::jsonb),
('CyberVolts', 'ECE - 2', 0, 'Registered', '{"password": "HZS2UY"}'::jsonb, 'Just now', '[]'::jsonb, '["Mohita N (ECE - 2)", "David Francis Royce Baker (ECE - 2)"]'::jsonb),
('Power Nexus', 'EEE - 3', 0, 'Registered', '{"password": "D5BUXU"}'::jsonb, 'Just now', '[]'::jsonb, '["Ashwin S (EEE - 3)", "Gokul N V (CSE - 3)"]'::jsonb),
('Simspace', 'EEE - 3', 0, 'Registered', '{"password": "HV4WBX"}'::jsonb, 'Just now', '[]'::jsonb, '["Additheya S (EEE - 3)"]'::jsonb),
('Oscorp', 'MECH - 2', 0, 'Registered', '{"password": "NDHLHH"}'::jsonb, 'Just now', '[]'::jsonb, '["Akash Palanivel (MECH - 2)", "Riyana Fernando (ECE - 2)"]'::jsonb),
('Adengapa rendu peru', 'BME - 3', 0, 'Registered', '{"password": "CJYVB5"}'::jsonb, 'Just now', '[]'::jsonb, '["P.Madhumetha (BME - 3)", "Krithika K (BME - 3)"]'::jsonb),
('Pixel Pulse', 'CSE - 2', 0, 'Registered', '{"password": "JY422R"}'::jsonb, 'Just now', '[]'::jsonb, '["PRENCY GEROLD (CSE - 2)", "PRAGADEESH K (CSE - 2)"]'::jsonb),
('Vasu n Saravanan', 'EEE - 2', 0, 'Registered', '{"password": "4QJMB3"}'::jsonb, 'Just now', '[]'::jsonb, '["Paramjeeth S (EEE - 2)", "Mogith A (ECE - 2)"]'::jsonb),
('Electra', 'ECE - 2', 0, 'Registered', '{"password": "SKQBBT"}'::jsonb, 'Just now', '[]'::jsonb, '["Raafiyah Gulshan A (ECE - 2)", "Hema K (EEE - 2)"]'::jsonb),
('Avenger', 'EEE - 3', 0, 'Registered', '{"password": "84SWJF"}'::jsonb, 'Just now', '[]'::jsonb, '["Yashasvee (EEE - 3)"]'::jsonb);
