-- SQL script to insert remaining 51 teams into Supabase 'teams' table
-- Run this script in your Supabase SQL Editor

INSERT INTO teams (name, institution, total_points, status, metrics, last_updated, run_history, tags)
VALUES
('Code Geass', 'EEE - 2', 0, 'Registered', '{"password": "HWGQ49"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Aamrrish G R (EEE - 2)', 'Mithul Pranav M (EEE - 2)']),
('Simvengers', 'BME - 2', 0, 'Registered', '{"password": "6RAFHU"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Anirudh H (BME - 2)', 'Gargi Pansari (BME - 2)']),
('Twinvolt', 'EEE - 3', 0, 'Registered', '{"password": "G6A9WP"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Mirthika S (EEE - 3)', 'Neha S (EEE - 3)']),
('Sana and Sugaa', 'EEE - 2', 0, 'Registered', '{"password": "3SYY2E"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Sahana Gopalakrishnan (EEE - 2)', 'Sugaasri S (EEE - 2)']),
('Double takkar', 'BME - 2', 0, 'Registered', '{"password": "XFUU7K"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Inbaa R (BME - 2)', 'Harshini.R.S (BME - 2)']),
('Royal super simulators', 'BME - 2', 0, 'Registered', '{"password": "VBZZ75"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Abhijeth (BME - 2)', 'Rithik (BME - 2)']),
('NOVA', 'ECE - 3', 0, 'Registered', '{"password": "F39H59"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Madeshwaran M (ECE - 3)', 'Janani M (ECE - 3)']),
('Supernova', 'BME - 2', 0, 'Registered', '{"password": "3S48BQ"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['GS Shai Manisha (BME - 2)', 'Shriya B (BME - 2)']),
('PulseForge', 'EEE - 3', 0, 'Registered', '{"password": "JDG58K"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Niveditha V (EEE - 3)', 'Pankaj Singh (EEE - 3)']),
('Sahana S', 'ECE - 2', 0, 'Registered', '{"password": "8QH78S"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Sahana S (ECE - 2)', 'Shri Bargavi S (ECE - 2)']),
('TeamX', 'EEE - 3', 0, 'Registered', '{"password": "3V835N"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Kesava Kailash M T (EEE - 3)']),
('Celestial', 'ECE - 2', 0, 'Registered', '{"password": "UTACK7"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Vikrant R.M (ECE - 2)']),
('Two phase', 'EEE - 2', 0, 'Registered', '{"password": "9ZNS97"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Perarasu.J (EEE - 2)', 'Vishnudharan.M (EEE - 2)']),
('Pairfect', 'BME - 3', 0, 'Registered', '{"password": "95CUW7"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Priscilla Christy S (BME - 3)', 'Kiruthika U (BME - 3)']),
('Simu Techiezz', 'ECE - 2', 0, 'Registered', '{"password": "G6S6M5"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Sanjay L (ECE - 2)', 'Sanjay S (ECE - 2)']),
('Sytrus', 'EEE - 2', 0, 'Registered', '{"password": "8ET9ZG"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Harshini Devi (EEE - 2)', 'Aashish S (EEE - 2)']),
('MATRIXMinds', 'EEE - 2', 0, 'Registered', '{"password": "N4K6AF"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Jaffy Sardonyx R (EEE - 2)', 'Madhumitha A (EEE - 2)']),
('Power Rangers', 'EEE - 2', 0, 'Registered', '{"password": "A6FNRH"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['R.Kritheesh (EEE - 2)', 'Antony Kilfrin Wilson (EEE - 2)']),
('DC', 'EEE - 2', 0, 'Registered', '{"password": "CTYKAW"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Lakshithnaren.S (EEE - 2)', 'Kishore M (EEE - 2)']),
('Dual Potential', 'ECE - 2', 0, 'Registered', '{"password": "9JQ8JU"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Shrivatsan Raja B (ECE - 2)', 'Sri Amrita B (ECE - 2)']),
('Steady State', 'ECE - 2', 0, 'Registered', '{"password": "F4LJV4"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Sakthi Sundara Murthy K S (ECE - 2)', 'Mahalakshmi K (ECE - 2)']),
('Matrixes', 'ECE - 2', 0, 'Registered', '{"password": "2KN2AG"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Aswin Sundaravadivelu (ECE - 2)']),
('Jarvis', 'ECE - 3', 0, 'Registered', '{"password": "2EDYYB"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Divyakriti Prabhu Uma (ECE - 3)', 'Aravind Krishna (ECE - 3)']),
('Earth616', 'EEE - 2', 0, 'Registered', '{"password": "B8WV6W"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Vibodh Ramanan (EEE - 2)', 'Pradhosh S (EEE - 2)']),
('No more mutants', 'EEE - 3', 0, 'Registered', '{"password": "H97LKP"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Mithreshwar CM (EEE - 3)', 'Jai muthukumaran J (EEE - 3)']),
('Ctrl+Alt+Defeat', 'MECH - 2', 0, 'Registered', '{"password": "5X7QE3"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['P Shreyas (MECH - 2)', 'Madhumita V J (CHEM - 2)']),
('okaynga', 'BME - 2', 0, 'Registered', '{"password": "CNMCD6"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Dhanya Mahalakshmi R (BME - 2)', 'Sharada Shree G (BME - 2)']),
('Simcy', 'EEE - 2', 0, 'Registered', '{"password": "N8BJPJ"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Hashim Mohamed Farook. H (EEE - 2)', 'Bharani. K (EEE - 2)']),
('Sync logic', 'EEE - 3', 0, 'Registered', '{"password": "LM2T54"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Prisca Jean D (EEE - 3)', 'Ramprasad B (EEE - 3)']),
('CodeCore', 'BME - 2', 0, 'Registered', '{"password": "F2VMYM"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Sreenithi S (BME - 2)', 'Ajay Karthic (BME - 2)']),
('Sharp Minds', 'ECE - 2', 0, 'Registered', '{"password": "S794U7"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Surya SS (ECE - 2)', 'Yashwanth Vijay (ECE - 2)']),
('Ohmies for Life', 'EEE - 3', 0, 'Registered', '{"password": "MW86HT"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['GOKULRAJ S L (EEE - 3)', 'ASHWAANTH R S (EEE - 3)']),
('S', 'EEE - 2', 0, 'Registered', '{"password": "GPQAF7"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Sanjay Vinayak (EEE - 2)']),
('Circuit Ninjas', 'ECE - 2', 0, 'Registered', '{"password": "X4MBYL"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['T Tharunn (ECE - 2)', 'Shivani M (ECE - 2)']),
('Matlab Mayavigal', 'ECE - 2', 0, 'Registered', '{"password": "YPHTPU"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Yuvaraj V (ECE - 2)', 'Srihari R V (ECE - 2)']),
('Kairova', 'CSE - 2', 0, 'Registered', '{"password": "TJGSG5"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Benita Brightly (CSE - 2)', 'Priyanka M (CSE - 2)']),
('Peanut Butter', 'EEE - 3', 0, 'Registered', '{"password": "LGDYMG"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Hemanth M (EEE - 3)', 'Faizaan M (EEE - 3)']),
('Simmates', 'ECE - 2', 0, 'Registered', '{"password": "WTEUWL"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['LAKSHMI PRIYA R (ECE - 2)', 'AKSHAYAA S A (ECE - 2)']),
('Tokyo Drifters', 'ECE - 3', 0, 'Registered', '{"password": "SSEA4S"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Vignesh Manikandan V (ECE - 3)', 'Shyam MR (ECE - 3)']),
('Dual sharks', 'BME - 2', 0, 'Registered', '{"password": "4ADGRB"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Rishmitha R (BME - 2)', 'Merlin Amrutha .E (BME - 2)']),
('Dual Sparks', 'BME - 2', 0, 'Registered', '{"password": "VHGYW7"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Merlin Amrutha E (BME - 2)', 'Rishmitha R (BME - 2)']),
('CannonBolt', 'BME - 2', 0, 'Registered', '{"password": "C3WP75"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Neha S (BME - 2)', 'Raja Anbu Chelvan A P (MECH - 2)']),
('CyberVolts', 'ECE - 2', 0, 'Registered', '{"password": "HZS2UY"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Mohita N (ECE - 2)', 'David Francis Royce Baker (ECE - 2)']),
('Power Nexus', 'EEE - 3', 0, 'Registered', '{"password": "D5BUXU"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Ashwin S (EEE - 3)', 'Gokul N V (CSE - 3)']),
('Simspace', 'EEE - 3', 0, 'Registered', '{"password": "HV4WBX"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Additheya S (EEE - 3)']),
('Oscorp', 'MECH - 2', 0, 'Registered', '{"password": "NDHLHH"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Akash Palanivel (MECH - 2)', 'Riyana Fernando (ECE - 2)']),
('Adengapa rendu peru', 'BME - 3', 0, 'Registered', '{"password": "CJYVB5"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['P.Madhumetha (BME - 3)', 'Krithika K (BME - 3)']),
('Pixel Pulse', 'CSE - 2', 0, 'Registered', '{"password": "JY422R"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['PRENCY GEROLD (CSE - 2)', 'PRAGADEESH K (CSE - 2)']),
('Vasu n Saravanan', 'EEE - 2', 0, 'Registered', '{"password": "4QJMB3"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Paramjeeth S (EEE - 2)', 'Mogith A (ECE - 2)']),
('Electra', 'ECE - 2', 0, 'Registered', '{"password": "SKQBBT"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Raafiyah Gulshan A (ECE - 2)', 'Hema K (EEE - 2)']),
('Avenger', 'EEE - 3', 0, 'Registered', '{"password": "84SWJF"}'::jsonb, 'Just now', '[]'::jsonb, ARRAY['Yashasvee (EEE - 3)']);
