import { Team } from "./types";

export const INITIAL_TEAMS: Team[] = [
  {
    id: "team-1",
    rank: 1,
    name: "APEX DYNAMICS",
    institution: "SSN Student Branch Chapter",
    totalPoints: 485,
    status: "System output validated. All parameter constraints met successfully.",
    metrics: {
      modelDesign: 92,
      simulationAccuracy: 88,
      systemPerformance: 75,
      innovation: 80,
      technicalApproach: 65,
      resultAnalysis: 45,
      presentation: 40,
    },
    lastUpdated: "5m ago",
    runHistory: [
      { run: 1, score: 380 },
      { run: 2, score: 420 },
      { run: 3, score: 485 },
    ],
    tags: ["PID", "Inverter", "LCL Filter"],
  },
  {
    id: "team-2",
    rank: 2,
    name: "KINETIC CHARGERS",
    institution: "CEG IEEE PES",
    totalPoints: 462,
    status: "Optimization complete. Minor harmonic distortion detected but within bounds.",
    metrics: {
      modelDesign: 85,
      simulationAccuracy: 90,
      systemPerformance: 72,
      innovation: 78,
      technicalApproach: 62,
      resultAnalysis: 40,
      presentation: 35,
    },
    lastUpdated: "12m ago",
    runHistory: [
      { run: 1, score: 390 },
      { run: 2, score: 410 },
      { run: 3, score: 462 },
    ],
    tags: ["Buck-Boost", "SMC", "High-Freq"],
  },
  {
    id: "team-3",
    rank: 3,
    name: "RESONANCE LABS",
    institution: "MIT IEEE PELS",
    totalPoints: 435,
    status: "Valid control loop feedback verified. High efficiency metrics recorded.",
    metrics: {
      modelDesign: 80,
      simulationAccuracy: 82,
      systemPerformance: 70,
      innovation: 75,
      technicalApproach: 58,
      resultAnalysis: 38,
      presentation: 32,
    },
    lastUpdated: "25m ago",
    runHistory: [
      { run: 1, score: 350 },
      { run: 2, score: 400 },
      { run: 3, score: 435 },
    ],
    tags: ["LLC Resonant", "Zero Voltage Switching"],
  },
  {
    id: "team-4",
    rank: 4,
    name: "VOLT MASTERS",
    institution: "IIT Madras PELS",
    totalPoints: 410,
    status: "Steady state reached with minimal overshoot. Verification complete.",
    metrics: {
      modelDesign: 78,
      simulationAccuracy: 76,
      systemPerformance: 68,
      innovation: 70,
      technicalApproach: 55,
      resultAnalysis: 35,
      presentation: 28,
    },
    lastUpdated: "40m ago",
    runHistory: [
      { run: 1, score: 310 },
      { run: 2, score: 375 },
      { run: 3, score: 410 },
    ],
    tags: ["SVPWM", "Three-Phase", "Grid-Tie"],
  },
  {
    id: "team-5",
    rank: 5,
    name: "SILICON PIONEERS",
    institution: "PSG Tech IEEE",
    totalPoints: 395,
    status: "Simulation execution completed. High transient response detected.",
    metrics: {
      modelDesign: 70,
      simulationAccuracy: 75,
      systemPerformance: 65,
      innovation: 65,
      technicalApproach: 50,
      resultAnalysis: 42,
      presentation: 28,
    },
    lastUpdated: "1h ago",
    runHistory: [
      { run: 1, score: 330 },
      { run: 2, score: 360 },
      { run: 3, score: 395 },
    ],
    tags: ["GaN", "SiC", "Thermal Simulation"],
  },
  {
    id: "team-6",
    rank: 6,
    name: "PID CONTROLLERS",
    institution: "VIT Vellore IEEE",
    totalPoints: 378,
    status: "Closed-loop system stable. Steady-state error minimized.",
    metrics: {
      modelDesign: 72,
      simulationAccuracy: 70,
      systemPerformance: 60,
      innovation: 62,
      technicalApproach: 48,
      resultAnalysis: 36,
      presentation: 30,
    },
    lastUpdated: "2h ago",
    runHistory: [
      { run: 1, score: 290 },
      { run: 2, score: 335 },
      { run: 3, score: 378 },
    ],
    tags: ["Classical PID", "Tuning", "Matlab App"],
  }
];
